---
controllers:
  controller_FR:
    controller_address: "/dev/ardu0"
  controller_FZ:
    controller_address: "/dev/ardu1"

motors:
  motor_FRF:
    controller: "controller_FR"
    index: 0
    sensor_index: 0
    gear_ratio_inv: 9
  motor_FRR:
    controller: "controller_FR"
    index: 1
    sensor_index: 1
    gear_ratio_inv: 9
  motor_FRZ:
    controller: "controller_FZ"
    index: 0
    sensor_index: 0
    gear_ratio_inv: 9

legs:
  leg_FR:
    motor_F: "motor_FRF"
    motor_B: "motor_FRR"
    motor_Z: "motor_FRZ"
    theta_p: 0.15
    theta_i: 0.20
    theta_d: 0.0
    gamma_p: 0.15
    gamma_i: 0.20
    gamma_d: 0.0
    z_p: 0.15
    z_i: 0.20
    z_d: 0.0